[package]
name = "path_finder"
version = "0.1.0"
authors = ["Bartłomiej Michalski <bartlomiej.j.michalski@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2.42"
web-sys = { version = "0.3.19", features = ['console'] }
js-sys = "0.3"
wee_alloc = { version = "0.4.2", optional = true }
futures ="0.1.28"
wasm-bindgen-futures ="0.3.25"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
opt-level = "s"
